[package]
name = "kgrs_const"
description = "Constant values for KaGRiS"
version = "0.1.0"
authors.workspace = true
license-file.workspace = true
repository = "https://github.com/Rinrin0413/KaGRiS/kgrs_const/"
readme.workspace = true
edition.workspace = true

[dependencies]
bevy = "0.9"
